# Optional theme settings

# Technologies to display on the front page banner.
# These should be font-awesome icons if possible
technologies:
    - html5
    - css3
    - git
    - linux

# A link to your GitHub profile. Should only contain
# the part after github.com/
github: sebastiaanfranken
